In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\customer_orders_raw_messy.csv")
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,150.0,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43.0,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27.0,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48.0,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,999.0,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

In [8]:
df.head(20)

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
5,1006,Arjun Mehta,150.0,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
6,1007,Rohit Gupta,43.0,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
7,1008,Amit Kumar,27.0,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
8,1009,Arjun Mehta,48.0,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
9,1010,Arjun Mehta,999.0,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1
10,1011,Arjun Mehta,39.0,Male,Indore,Rajasthan,user10@gmail.com,9889978790,2025-01-10,2025-01-15,Printer,Accessories,1,1000,0.05,950.0,Cash,5
11,1012,Rohit Gupta,44.0,Female,Pune,Maharashtra,user11@gmail.com,9849392920,2025-01-10,2025-01-15,Mouse,electronics,-2,20000,0.00,20000.0,Cash,1
12,1013,Rohit Gupta,49.0,Male,Jaipur,Uttar Pradesh,user12@gmail.com,9878137358,2025-01-10,2025-01-15,Desk,electronics,3,10000,0.05,28500.0,UPI,3
13,1014,Amit Kumar,39.0,Female,Lucknow,Maharashtra,user13@gmail.com,9825014631,2025-01-10,2025-01-15,Keyboard,Furniture,2,10000,0.20,16000.0,Cash,2
14,1015,Priya Sharma,22.0,Female,Delhi,Madhya Pradesh,user14@gmail.com,9826879290,2025-01-10,2025-01-15,Headphones,accessories,1,1000,0.20,800.0,Cash,5
15,1016,Kiran Shah,33.0,Male,Surat,Uttar Pradesh,user15@gmail.com,12345,2025-01-10,2025-01-15,Mouse,accessories,2,2500,0.20,4000.0,Credit Card,3
16,1017,Priya Sharma,27.0,Male,Delhi,Gujarat,user16@gmail.com,9812823170,2025-01-10,2025-01-15,Desk,Accessories,4,10000,0.15,34000.0,UPI,5
17,1018,Amit Kumar,27.0,Male,Mumbai,Gujarat,user17@gmail.com,9819510312,2025-01-10,2025-01-15,Chair,electronics,2,500,0.00,1000.0,Cash,4
18,1019,Kiran Shah,38.0,Female,Surat,Rajasthan,user18@gmail.com,9864634663,2025-01-10,2025-01-15,Tablet,Electronics,2,10000,0.05,19000.0,UPI,4
19,1020,Sneha Jain,47.0,Male,Delhi,Maharashtra,user19@gmail.com,9864038913,2025-01-10,2025-01-15,Keyboard,Furniture,3,5000,0.15,12750.0,UPI,2

In [9]:
df.shape

(310, 18)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        310 non-null    int64
 1   Customer_Name   310 non-null    object
 2   Age             306 non-null    float64
 3   Gender          310 non-null    object
 4   City            310 non-null    object
 5   State           310 non-null    object
 6   Email           310 non-null    object
 7   Phone           310 non-null    object
 8   Order_Date      310 non-null    object
 9   Delivery_Date   310 non-null    object
 10  Product         310 non-null    object
 11  Category        310 non-null    object
 12  Quantity        310 non-null    int64
 13  Price           310 non-null    int64
 14  Discount        310 non-null    float64
 15  Revenue         310 non-null    float64
 16  Payment_Method  310 non-null    object
 17  Rating          310 non-null    int64
dtypes: float64(3), int64(4), object(11)
memory usage: 43.7+ KB

In [11]:
df.describe()

,Order_ID,Age,Quantity,Price,Discount,Revenue,Rating
count,310.000000,306.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,1145.822581,54.238562,2.667742,12311.290323,0.103871,30323.870968,3.041935
std,89.107862,135.157875,1.718712,15500.726623,0.069798,42893.645270,1.605467
min,1001.000000,-5.000000,-2.000000,500.000000,0.000000,425.000000,0.000000
25%,1068.250000,27.000000,1.000000,1000.000000,0.050000,3800.000000,2.000000
50%,1145.500000,34.000000,3.000000,5000.000000,0.100000,13500.000000,3.000000
75%,1222.750000,41.000000,4.000000,20000.000000,0.150000,37500.000000,4.000000
max,1300.000000,999.000000,5.000000,50000.000000,0.200000,200000.000000,10.000000

# Missing Values

In [12]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
Age               4
Gender            0
City              0
State             0
Email             0
Phone             0
Order_Date        0
Delivery_Date     0
Product           0
Category          0
Quantity          0
Price             0
Discount          0
Revenue           0
Payment_Method    0
Rating            0
dtype: int64

In [13]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
305     True
306     True
307     True
308     True
309     True
Length: 310, dtype: bool

In [14]:
df['Gender'].unique

<bound method Series.unique of 0        Male
1        Male
2      Female
3      Female
4        Male
        ...
305    Female
306      Male
307      Male
308    Female
309    Female
Name: Gender, Length: 310, dtype: object>

In [15]:
df['Category'].unique

<bound method Series.unique of 0      Accessories
1       Electronic
2        Furniture
3      Electronics
4        Furniture
          ...
305    electronics
306    accessories
307    electronics
308    accessories
309     Electronic
Name: Category, Length: 310, dtype: object>

In [16]:
df['Payment_Method'].unique

<bound method Series.unique of 0             Cash
1              UPI
2             Cash
3             Cash
4             Cash
          ...
305    Credit Card
306    Credit Card
307    Credit Card
308    Credit Card
309            UPI
Name: Payment_Method, Length: 310, dtype: object>

In [20]:
df.head()

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1

# Fix Customer_name

In [30]:
df['Customer_Name'] = df['Customer_Name'].str.strip()
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,150.0,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43.0,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27.0,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48.0,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,999.0,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

# Fix Age

In [31]:
df['Age'].describe()

count    306.000000
mean      54.238562
std      135.157875
min       -5.000000
25%       27.000000
50%       34.000000
75%       41.000000
max      999.000000
Name: Age, dtype: float64

In [34]:
import numpy as np

In [37]:
import numpy as np

df["Age"] = np.where(
    (df["Age"] < 18) |
    (df["Age"] > 80),
    np.nan,
    df["Age"]
)
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,NaN,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43.0,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27.0,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48.0,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,NaN,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

In [45]:
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

# Fix Gender

In [47]:
df['Gender'].value_counts(dropna = False)

Gender
Male      162
Female    148
Name: count, dtype: int64

# Fix City

In [50]:
df['City'].value_counts(dropna = False)

City
Delhi        51
Indore       49
Ahmedabad    37
Jaipur       35
Pune         34
Surat        32
Lucknow      29
Mumbai       28
 Jaipur       7
 Mumb@i       4
Delh!i        4
Name: count, dtype: int64

In [61]:
df['City'] =df['City'].str.strip()
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

In [69]:
df['City'] =df['City'].replace({'Mumb@i':'Mumbai'}).astype('string')
df['City'].value_counts(dropna = False)

City
Delhi        55
Indore       49
Jaipur       42
Ahmedabad    37
Pune         34
Surat        32
Mumbai       32
Lucknow      29
Name: count, dtype: Int64

# Fix Gender

In [76]:

df['City'] = df['City'].str.strip()
df['Gender'].value_counts(dropna = False)

Gender
Male      162
Female    148
Name: count, dtype: int64

 # Fix State

In [78]:
df['State'] = df['State'].str.strip()
df['State'].value_counts(dropna = False)

State
Maharashtra       59
Gujarat           55
Rajasthan         49
Uttar Pradesh     47
Delhi             47
Madhya Pradesh    38
GJ                 7
gujrat             5
GUJRAT             3
Name: count, dtype: int64

In [ ]:
df['State'] = df['State'].replace({'GJ':'Gujarat','gujrat':'Gujarat','GUJRAT':'Gujarat'})
df['State'].value_counts(dropna = False)
df

# Fix Email

In [87]:
df['Email'] = df['Email'].str.strip()
df['Email'] = df['Email'].str.lower()
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

# Fix Phone no

df["Phone"] = df["Phone"].astype(str)
df["Phone"].str.len()
df[df["Phone"].str.len() != 10]
df[df["Phone"].str.isnumeric() == False]
df["Phone_Valid"] = (
    (df["Phone"].str.len() == 10)
    &
    (df["Phone"].str.isnumeric())
)
df[["Phone","Phone_Valid"]]
import numpy as np

df.loc[
    df["Phone_Valid"] == False,
    "Phone"
] = np.nan

df["Phone"].isnull().sum()
df

In [97]:
df["Phone"].isnull().sum()

np.int64(15)

# Fix Product

In [101]:
df['Product'] = df['Product'].str.strip()
df
df['Product'].value_counts(dropna = False )

Product
Chair         36
Keyboard      36
Tablet        35
Mobile        31
Monitor       31
Mouse         30
Printer       29
Headphones    29
Desk          27
Laptop        26
Name: count, dtype: int64

# Fix Category

In [106]:
df['Category'] = df['Category'].str.strip()
df[	'Category'].value_counts(dropna =False)

Category
Furniture      53
Accessories    51
accessories    47
electronics    43
ELECTRONICS    42
Electronic     41
Electronics    33
Name: count, dtype: int64

In [110]:
df[	'Category'] = df[	'Category'].replace({'accessories':'Accessories','electronics':'Electronics','ELECTRONICS':'Electronics','Electronic':'Electronics',})
df[	'Category'].value_counts(dropna =False)
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0,True
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,Electronics,0,50000,0.00,100000.0,Credit Card,3,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,Accessories,-2,20000,0.15,34000.0,Credit Card,5,True
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True

# FIX  Revenue

In [122]:
df[	'Revenue'].value_counts(dropna =False)
df.sort_values('Revenue')
df["Revenue_Valid"] = (
    df["Revenue"] ==
    (df["Quantity"] * df["Price"] * (1 - df["Discount"]))
)
df["Revenue_Valid"].value_counts()
df["Revenue"] = (
    df["Quantity"] *
    df["Price"] *
    (1 - df["Discount"])
).round(2)

df["Revenue_Valid"].value_counts()
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid,Revenue_Valid
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0,True,True
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,Electronics,0,50000,0.00,0.0,Credit Card,3,True,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True,True
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,Accessories,-2,20000,0.15,-34000.0,Credit Card,5,True,True
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True,True

# Fix Quantity

In [123]:
df['Quantity'].value_counts( dropna = False)

Quantity
 1    68
 3    66
 5    57
 2    54
 4    48
-2    12
 0     5
Name: count, dtype: int64

In [125]:

df[df["Quantity"] <= 0]

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid,Revenue_Valid
5,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,Electronics,0,50000,0.00,0.0,Credit Card,3,True,True
8,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,Accessories,-2,20000,0.15,-34000.0,Credit Card,5,True,True
11,1012,Rohit Gupta,44,Female,Pune,Maharashtra,user11@gmail.com,9849392920,2025-01-10,2025-01-15,Mouse,Electronics,-2,20000,0.00,-40000.0,Cash,1,True,True
43,1044,Neha Patel,42,Female,Lucknow,Rajasthan,user43@gmail.com,9842747037,2025-01-10,2025-01-15,Headphones,Accessories,-2,5000,0.20,-8000.0,Credit Card,1,True,True
81,1082,Rohit Gupta,42,Female,Indore,Rajasthan,user81@gmail.com,9873380266,2025-01-10,2025-01-15,Tablet,Electronics,-2,20000,0.10,-36000.0,Credit Card,2,True,True
92,1093,Neha Patel,32,Female,Delhi,Delhi,user92@gmail.com,9861185849,2025-01-10,2025-01-15,Desk,Electronics,-2,5000,0.10,-9000.0,Credit Card,3,True,True
127,1128,Vikram Joshi,38,Male,Pune,Madhya Pradesh,user127@gmail.com,9819957701,2025-01-10,2025-01-15,Monitor,Electronics,-2,20000,0.10,-36000.0,Cash,1,True,True
151,1152,Vikram Joshi,45,Male,Indore,Maharashtra,user151@gmail.com,9867795113,2025-01-10,2025-01-15,Desk,Furniture,-2,50000,0.20,-80000.0,UPI,5,True,True
186,1187,Sneha Jain,35,Male,Jaipur,Gujarat,user186@gmail.com,9848307798,2025-01-10,2025-01-15,Laptop,Furniture,-2,1000,0.15,-1700.0,UPI,5,True,True
203,1204,Neha Patel,34,Male,Indore,Rajasthan,user203@gmail.com,9841452485,2025-01-10,2025-01-15,Chair,Electronics,-2,10000,0.00,-20000.0,UPI,2,True,True
208,1209,Sneha Jain,47,Female,Delhi,Gujarat,user208@gmail.com,9835566010,2025-01-10,2025-01-15,Laptop,Electronics,-2,2500,0.00,-5000.0,Cash,5,True,True
243,1244,Neha Patel,34,Female,Indore,Maharashtra,user243@gmail.com,9838829445,2025-01-10,2025-01-15,Tablet,Electronics,-2,500,0.20,-800.0,Credit Card,1,True,True
254,1255,Rohit Gupta,28,Male,Pune,Uttar Pradesh,user254@gmail.com,9849276764,2025-01-10,2025-01-15,Monitor,Accessories,0,10000,0.10,0.0,Cash,5,True,True
271,1272,Rohit Gupta,49,Male,Ahmedabad,Madhya Pradesh,user271@gmail.com,9853855682,2025-01-10,2025-01-15,Mouse,Accessories,0,2500,0.00,0.0,Credit Card,1,True,True
281,1282,Pooja Verma,20,Female,Jaipur,Maharashtra,user281@gmail.com,NaN,2025-01-10,2025-01-15,Chair,Electronics,0,20000,0.00,0.0,Cash,4,False,True
305,1006,Arjun Mehta,34,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,Electronics,0,50000,0.00,0.0,Credit Card,3,True,True
308,1009,Arjun Mehta,48,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,Accessories,-2,20000,0.15,-34000.0,Credit Card,5,True,True

In [126]:
(df["Quantity"] <= 0).sum()

np.int64(17)

In [127]:
df = df[df["Quantity"] > 0]

In [130]:
df["Quantity"].value_counts(dropna=False)

Quantity
1    68
3    66
5    57
2    54
4    48
Name: count, dtype: int64

In [131]:
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid,Revenue_Valid
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0,True,True
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
304,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True,True
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True,True

 # Fix Rating

In [132]:
df["Rating"].value_counts(dropna=False)

Rating
4     65
1     62
3     59
5     54
2     42
0      6
6      3
10     2
Name: count, dtype: int64

In [133]:
df = df[df["Rating"] <= 5]

In [134]:
df["Rating"].value_counts(dropna=False)

Rating
4    65
1    62
3    59
5    54
2    42
0     6
Name: count, dtype: int64

In [136]:
df = df[df["Rating"] != 0]
df["Rating"].value_counts(dropna=False)

Rating
4    65
1    62
3    59
5    54
2    42
Name: count, dtype: int64

In [137]:
df = df[(df["Rating"] >= 1) & (df["Rating"] <= 5)]

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 282 entries, 1 to 309
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        282 non-null    int64
 1   Customer_Name   282 non-null    object
 2   Age             282 non-null    int64
 3   Gender          282 non-null    object
 4   City            282 non-null    string
 5   State           282 non-null    object
 6   Email           282 non-null    object
 7   Phone           268 non-null    object
 8   Order_Date      282 non-null    object
 9   Delivery_Date   282 non-null    object
 10  Product         282 non-null    object
 11  Category        282 non-null    object
 12  Quantity        282 non-null    int64
 13  Price           282 non-null    int64
 14  Discount        282 non-null    float64
 15  Revenue         282 non-null    float64
 16  Payment_Method  282 non-null    object
 17  Rating          282 non-null    int64
 18  Phone_Valid     282 non-null    bool
 19  Revenue_Valid   282 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(10), string(1)
memory usage: 42.4+ KB

# Inspect Date Columns

In [139]:
df[["Order_Date", "Delivery_Date"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 282 entries, 1 to 309
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Date     282 non-null    object
 1   Delivery_Date  282 non-null    object
dtypes: object(2)
memory usage: 6.6+ KB

In [140]:
df["Order_Date"].dtype
df["Delivery_Date"].dtype

dtype('O')

In [141]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")
df["Order_Date"].dtype

dtype('<M8[ns]')

In [145]:
(df["Delivery_Date"] < df["Order_Date"]).sum()

np.int64(0)

In [146]:
df.to_csv("customer_orders_cleaned.csv", index=False)

In [147]:
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid,Revenue_Valid
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
6,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
304,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True,True
309,1010,Arjun Mehta,34,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True,True

In [148]:
import os

os.getcwd()

'C:\\Users\\ASUS'