In [4]:
import pandas as pd

In [5]:
df =pd.read_csv(r"C:\Users\ASUS\Downloads\customer_orders_raw_messy.csv")
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating
0,1001,Neha Patel,27.0,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0
1,1002,Neha Patel,36.0,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronic,1,500,0.05,475.0,UPI,4
2,1003,Rahul Singh,42.0,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1
3,1004,Pooja Verma,47.0,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1
4,1005,Pooja Verma,38.0,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1006,Arjun Mehta,150.0,Female,Pune,Delhi,user5@gmail.com,9859684848,2025-01-10,2025-01-15,Keyboard,electronics,0,50000,0.00,100000.0,Credit Card,3
306,1007,Rohit Gupta,43.0,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,accessories,1,10000,0.05,9500.0,Credit Card,5
307,1008,Amit Kumar,27.0,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,electronics,2,20000,0.10,36000.0,Credit Card,3
308,1009,Arjun Mehta,48.0,Female,Ahmedabad,Gujarat,user8@gmail.com,9828740864,2025-01-10,2025-01-15,Tablet,accessories,-2,20000,0.15,34000.0,Credit Card,5
309,1010,Arjun Mehta,999.0,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronic,3,20000,0.20,48000.0,UPI,1

In [6]:
df.shape

(310, 18)

# Change Type

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        310 non-null    int64
 1   Customer_Name   310 non-null    object
 2   Age             306 non-null    float64
 3   Gender          310 non-null    object
 4   City            310 non-null    object
 5   State           310 non-null    object
 6   Email           310 non-null    object
 7   Phone           310 non-null    object
 8   Order_Date      310 non-null    object
 9   Delivery_Date   310 non-null    object
 10  Product         310 non-null    object
 11  Category        310 non-null    object
 12  Quantity        310 non-null    int64
 13  Price           310 non-null    int64
 14  Discount        310 non-null    float64
 15  Revenue         310 non-null    float64
 16  Payment_Method  310 non-null    object
 17  Rating          310 non-null    int64
dtypes: float64(3), int64(4), object(11)
memory usage: 43.7+ KB

In [7]:
df['Order_ID']=df['Order_ID'].astype (str)
df['Customer_Name']=df['Customer_Name'].astype (str)
df['Age']=df['Age'].astype (float)
df['Order_Date']= pd.to_datetime(df['Order_Date'], errors='coerce')
df['Delivery_Date']= pd.to_datetime(df['Delivery_Date'], errors='coerce')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        310 non-null    object
 1   Customer_Name   310 non-null    object
 2   Age             306 non-null    float64
 3   Gender          310 non-null    object
 4   City            310 non-null    object
 5   State           310 non-null    object
 6   Email           310 non-null    object
 7   Phone           310 non-null    object
 8   Order_Date      300 non-null    datetime64[ns]
 9   Delivery_Date   310 non-null    datetime64[ns]
 10  Product         310 non-null    object
 11  Category        310 non-null    object
 12  Quantity        310 non-null    int64
 13  Price           310 non-null    int64
 14  Discount        310 non-null    float64
 15  Revenue         310 non-null    float64
 16  Payment_Method  310 non-null    object
 17  Rating          310 non-null    int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(10)
memory usage: 43.7+ KB

# Fix Customer Name

In [8]:
df["Customer_Name"] = (
    df["Customer_Name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

# Fix Age

In [9]:
df['Age'].value_counts()

Age
 27.0     16
 30.0     15
 22.0     15
 38.0     15
 39.0     14
 29.0     14
 24.0     13
 33.0     13
 20.0     12
 25.0     11
 40.0     11
 43.0     11
 28.0      9
 34.0      9
 45.0      9
 23.0      8
 41.0      8
 42.0      8
 36.0      8
 21.0      8
 50.0      7
 46.0      7
 35.0      7
 49.0      6
 999.0     6
 37.0      6
 150.0     6
 32.0      6
 47.0      6
 0.0       5
 44.0      5
 48.0      5
 31.0      3
 26.0      3
-5.0       1
Name: count, dtype: int64

In [10]:
import numpy as np

In [11]:
df['Age'] = np.where( (df['Age'] <18) |
                     ( df['Age'] >80),
                      np.nan,
                      df['Age'] )

In [12]:
df['Age'] = df['Age'].fillna((df['Age'].mean()))
df['Age']= df['Age'].astype(int)

In [13]:
df['Age'].value_counts()

Age
33    35
27    16
38    15
30    15
22    15
29    14
39    14
24    13
20    12
40    11
43    11
25    11
34     9
28     9
45     9
36     8
21     8
23     8
41     8
42     8
46     7
50     7
35     7
49     6
32     6
47     6
37     6
44     5
48     5
31     3
26     3
Name: count, dtype: int64

# Fix Gender

In [14]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

# Fix City

In [15]:
df['City'].unique()

array(['Delhi', 'Surat', 'Pune', 'Jaipur', 'Ahmedabad', 'Indore',
       'Lucknow', 'Mumbai', ' Jaipur ', ' Mumb@i ', 'Delh!i'],
      dtype=object)

In [16]:
df['City']=df['City'].replace({' Mumb@i ':'Mumbai','Delh!i':'Delhi'})

In [17]:
df['City'] =df['City'].str.strip()
df['City'].unique()

array(['Delhi', 'Surat', 'Pune', 'Jaipur', 'Ahmedabad', 'Indore',
       'Lucknow', 'Mumbai'], dtype=object)

# Fix State

In [18]:
df['State'] =df['State'].str.strip()
df['State'].unique()

array(['Uttar Pradesh', 'Gujarat', 'Maharashtra', 'Delhi', 'Rajasthan',
       'Madhya Pradesh', 'GJ', 'gujrat', 'GUJRAT'], dtype=object)

In [19]:
df['State'] = df['State'].replace({'GJ':'Gujarat','gujrat':'Gujarat','GUJRAT':'Gujarat'})
df['State'].unique()

array(['Uttar Pradesh', 'Gujarat', 'Maharashtra', 'Delhi', 'Rajasthan',
       'Madhya Pradesh'], dtype=object)

# Fix Email

In [20]:
df['Email'] = df['Email'].str.strip()
df['Email'] = df['Email'].str.lower()
df['Email'].isnull().sum()

np.int64(0)

# Fix Product

In [21]:
df['Product']=df['Product'].str.strip()
df['Product'].unique()

array(['Mobile', 'Chair', 'Tablet', 'Keyboard', 'Monitor', 'Printer',
       'Mouse', 'Desk', 'Headphones', 'Laptop'], dtype=object)

# Fix Category

In [23]:
df['Category'] =df['Category'].str.strip()
df['Category'].unique()

array(['Accessories', 'Electronic', 'Furniture', 'Electronics',
       'electronics', 'accessories', 'ELECTRONICS'], dtype=object)

In [28]:
df[	'Category'] = df[	'Category'].replace({'accessories':'Accessories','electronics':'Electronics','ELECTRONICS':'Electronics','Electronic':'Electronics',})
df['Category'].unique()

array(['Accessories', 'Electronics', 'Furniture'], dtype=object)

# Fix Quantity

In [29]:
df['Quantity'].unique()

array([ 1,  5,  0,  2, -2,  3,  4])

In [34]:
df['Quantity'].value_counts().sort_index()

Quantity
-2    12
 0     5
 1    68
 2    54
 3    66
 4    48
 5    57
Name: count, dtype: int64

In [49]:
 df = df[df['Quantity'] >=1]

In [50]:
df['Quantity'].unique()

array([1, 5, 2, 3, 4])

# Fix Phone

In [51]:
df['Phone'] = df['Phone'].str.strip()
df['Phone'] = df['Phone'].astype(str)

In [47]:
df1 = df[df['Quantity'] >= 1].copy()

In [48]:
df['Phone'] = df['Phone'].str.strip()
df['Phone'] = df['Phone'].astype(str)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13088\3827756019.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone'] = df['Phone'].str.strip()
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13088\3827756019.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone'] = df['Phone'].astype(str)

In [52]:
df = df[df['Quantity'] >= 1].copy()

In [54]:
df['Phone'] = df['Phone'].str.strip()
df['Phone'] = df['Phone'].astype(str)

In [55]:
df['Phone_Valid'] =( (df['Phone'].str.len() ==10)& (df['Phone'].str.isnumeric()))

In [60]:
df= df[df['Phone_Valid'] == True]
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0,True
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True
304,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True
309,1010,Arjun Mehta,33,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True

# Fix Revenue

In [65]:
df['Reveune_Valid']= ( df['Revenue'] == ((df['Quantity']*df['Price'])*(1-df['Discount'])))

In [66]:
df['Reveune_Valid'].value_counts()

Reveune_Valid
True    279
Name: count, dtype: int64

# Fix Date

In [71]:
df["Order_Date"].dtype
df['Delivery_Date'].dtype

dtype('<M8[ns]')

In [73]:
(df["Delivery_Date"] > df["Order_Date"]).sum()

np.int64(270)

In [74]:
df

,Order_ID,Customer_Name,Age,Gender,City,State,Email,Phone,Order_Date,Delivery_Date,Product,Category,Quantity,Price,Discount,Revenue,Payment_Method,Rating,Phone_Valid,Reveune_Valid
0,1001,Neha Patel,27,Male,Delhi,Uttar Pradesh,user0@gmail.com,9883197857,2025-01-10,2025-01-15,Mobile,Accessories,1,500,0.10,450.0,Cash,0,True,True
1,1002,Neha Patel,36,Male,Surat,Uttar Pradesh,user1@gmail.com,9897226012,2025-01-10,2025-01-15,Chair,Electronics,1,500,0.05,475.0,UPI,4,True,True
2,1003,Rahul Singh,42,Female,Pune,Gujarat,user2@gmail.com,9830868105,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.00,12500.0,Cash,1,True,True
3,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
4,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,1004,Pooja Verma,47,Female,Jaipur,Maharashtra,user3@gmail.com,9871662963,2025-01-10,2025-01-15,Chair,Electronics,1,5000,0.00,5000.0,Cash,1,True,True
304,1005,Pooja Verma,38,Male,Delhi,Maharashtra,user4@gmail.com,9898753260,2025-01-10,2025-01-15,Tablet,Furniture,5,2500,0.20,10000.0,Cash,1,True,True
306,1007,Rohit Gupta,43,Male,Ahmedabad,Rajasthan,user6@gmail.com,9860929647,2025-01-10,2025-01-15,Monitor,Accessories,1,10000,0.05,9500.0,Credit Card,5,True,True
307,1008,Amit Kumar,27,Male,Pune,Rajasthan,user7@gmail.com,9845935572,2025-01-10,2025-01-15,Mobile,Electronics,2,20000,0.10,36000.0,Credit Card,3,True,True
309,1010,Arjun Mehta,33,Female,Pune,Delhi,user9@gmail.com,9828566572,2025-01-10,2025-01-15,Chair,Electronics,3,20000,0.20,48000.0,UPI,1,True,True

# NumPy Feature Engineering.

# Group by Age

In [75]:
df['Age_Group'] = np.where(df['Age']<30,'Young',np.where(df['Age']<50,'Adult','Senior'))

In [78]:
df['Age_Group'].value_counts().sort_values()

Age_Group
Senior      7
Young     100
Adult     172
Name: count, dtype: int64

# VIP Customer

In [79]:
df['VIP_Customer'] = np.where(df['Revenue'] >30000 ,'Yes','No')

In [80]:
df['VIP_Customer'].value_counts().sort_values()

VIP_Customer
Yes     82
No     197
Name: count, dtype: int64

# High Rating

In [81]:
df['High_Rating'] = np.where(df['Rating'] >4 ,'Yes','No')

In [82]:
df['High_Rating'].value_counts().sort_values()

High_Rating
Yes     58
No     221
Name: count, dtype: int64

In [83]:
df.to_csv("customer_orders_cleaned.csv", index=False)

In [ ]:
df.to_excel("customer_orders_cleaned.xlsx", index=False)